name: Release

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Version tags"

env:
  APP_NAME: "neo"
  PACK_FLAG: ""
  PACK_ENV: "/app/pack.docker.yao"

jobs:
  release:
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: yaoapp/yao-build:0.10.3-amd64
          options: -v ${{ github.workspace }}:/app -e APP_NAME=${{ env.APP_NAME }} -e PACK_ENV=${{ env.PACK_ENV }}
          run: |
            echo "Running Build"
            make

      - name: Archive AMD64
        uses: actions/upload-artifact@v3
        with:
          name: neo-0.10.3-linux-amd64
          path: |
            dist/neo-0.10.3-linux-amd64

      - name: Archive ARM64
        uses: actions/upload-artifact@v3
        with:
          name: neo-0.10.3-linux-arm64
          path: |
            dist/neo-0.10.3-linux-arm64
